title: echu's site

# avoid "but it works locally"
--safe: true

# dump _pages into root
collections:
  pages:
    output: true
    permalink: /:path

permalink: /blog/:year/:month/:day/:title

sass:
  sass_dir: styles